// Generated by gencpp from file fashionstar_uart_servo_ros1/QueryServoAngle.msg
// DO NOT EDIT!


#ifndef FASHIONSTAR_UART_SERVO_ROS1_MESSAGE_QUERYSERVOANGLE_H
#define FASHIONSTAR_UART_SERVO_ROS1_MESSAGE_QUERYSERVOANGLE_H

#include <ros/service_traits.h>


#include <fashionstar_uart_servo_ros1/QueryServoAngleRequest.h>
#include <fashionstar_uart_servo_ros1/QueryServoAngleResponse.h>


namespace fashionstar_uart_servo_ros1
{

struct QueryServoAngle
{

typedef QueryServoAngleRequest Request;
typedef QueryServoAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryServoAngle
} // namespace fashionstar_uart_servo_ros1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngle > {
  static const char* value()
  {
    return "3fa0610a2c670f4fbf342f6899c09e8c";
  }

  static const char* value(const ::fashionstar_uart_servo_ros1::QueryServoAngle&) { return value(); }
};

template<>
struct DataType< ::fashionstar_uart_servo_ros1::QueryServoAngle > {
  static const char* value()
  {
    return "fashionstar_uart_servo_ros1/QueryServoAngle";
  }

  static const char* value(const ::fashionstar_uart_servo_ros1::QueryServoAngle&) { return value(); }
};


// service_traits::MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngleRequest> should match
// service_traits::MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngle >
template<>
struct MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngle >::value();
  }
  static const char* value(const ::fashionstar_uart_servo_ros1::QueryServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fashionstar_uart_servo_ros1::QueryServoAngleRequest> should match
// service_traits::DataType< ::fashionstar_uart_servo_ros1::QueryServoAngle >
template<>
struct DataType< ::fashionstar_uart_servo_ros1::QueryServoAngleRequest>
{
  static const char* value()
  {
    return DataType< ::fashionstar_uart_servo_ros1::QueryServoAngle >::value();
  }
  static const char* value(const ::fashionstar_uart_servo_ros1::QueryServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngleResponse> should match
// service_traits::MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngle >
template<>
struct MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fashionstar_uart_servo_ros1::QueryServoAngle >::value();
  }
  static const char* value(const ::fashionstar_uart_servo_ros1::QueryServoAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fashionstar_uart_servo_ros1::QueryServoAngleResponse> should match
// service_traits::DataType< ::fashionstar_uart_servo_ros1::QueryServoAngle >
template<>
struct DataType< ::fashionstar_uart_servo_ros1::QueryServoAngleResponse>
{
  static const char* value()
  {
    return DataType< ::fashionstar_uart_servo_ros1::QueryServoAngle >::value();
  }
  static const char* value(const ::fashionstar_uart_servo_ros1::QueryServoAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASHIONSTAR_UART_SERVO_ROS1_MESSAGE_QUERYSERVOANGLE_H
